### ISSUE TITLE
Page type I18n missing 

### ISSUE THREAD

**Issue by aniramina** [netzmacht/contao-i18n#2]
I just installed your extension using contao-manager and tried to create a page of Type I18n but the list of page-types offered only gives the same as in a basic contao-installation:

regular, internal redirect, external redirect, logout, 404, 403 - no I18n regular page. 
Is this behaviour correct?  

Contao 4.4.19 managed edition running on ubuntu 16.04 server, php 7.1.18, contao-i18n ver 2.0.0 

Any help/ hint where to search for the problem's cause is welcome
Thx, Marina

**Comment by dmolineus** [comment]
The i18n page is not available in the main language. It's meant for the translated pages. You should check if you properly connected your root pages as required by changelanguage.

**Comment by dmolineus** [comment]
Closed because of missing answer. Fee free to open a new issue with requested information.
