### ISSUE TITLE
White/blank INSTALL-page

### ISSUE THREAD

**Issue by koopoo69** [netzmacht/contao-i18n#4]
Dear support, 
I installed contao-i18n successfully under Contao 4.9 ... but as soon as I try to update the database on the install-page I get a white/blank result. Why? Many thanx for supporting ...

**Comment by dmolineus** [comment]
Your error log (`var/logs/prod.log`) could tell more or even better open the install tool in the `dev mode`. The extension was developed for Contao 4.4, so you probably run into a incompatibility issue with Contao 4.9.

**Comment by dmolineus** [comment]
Can't be reproduced. A new upcoming version for Contao 4.13 is coming. The extension won't support 4.9 anymore.
